version: 2

jobs:
  build:
    docker:
      - image: martinthomson/neqo:latest

    steps:
      - checkout

      - run:
          name: Show Versions
          command: |
            rustup show
            rustup --version
            rustc --version
            cargo --version
            rustfmt --version

      - run:
          name: Check Formatting
          command: cargo fmt -- --check

      - run:
          name: Build
          command: cargo build

      - run:
          name: Test
          command: cargo test
