[package]
name = "neqo-transport"
version = "0.1.0"
authors = ["EKR <ekr@rtfm.com>"]
edition = "2018"
          
[dependencies]
neqo-crypto = { version = "0.1", path = "../neqo-crypto" }
num-traits = "0.2"
derive_more = "0.13"
lazy_static = "1.0"
